### ISSUE TITLE
Error 500 after pressing the Push button

### ISSUE THREAD

**Issue by declicromania** [GetUp/identity-spoke#1]
Everything seems to work, the spoke campaigns are correctly shown in Identity, but when pushing the Push button the screen goes to 500 error and the following log is generated:

`F, [2019-08-06T11:37:36.868404 #7] FATAL -- : [eebfb355-8340-407c-8d76-71274b6ef96b]
F, [2019-08-06T11:37:36.868729 #7] FATAL -- : [eebfb355-8340-407c-8d76-71274b6ef96b] ActionView::Template::Error (wrong number of arguments (given 2, expected 3)):
F, [2019-08-06T11:37:36.869052 #7] FATAL -- : [eebfb355-8340-407c-8d76-71274b6ef96b]     46:         <%- @list.syncs.each do |sync| %>
[eebfb355-8340-407c-8d76-71274b6ef96b]     47:           <div>
[eebfb355-8340-407c-8d76-71274b6ef96b]     48:             <i class="glyphicon glyphicon-transfer"></i>
[eebfb355-8340-407c-8d76-71274b6ef96b]     49:             <%= sync.description %>
[eebfb355-8340-407c-8d76-71274b6ef96b]     50:           </div>
[eebfb355-8340-407c-8d76-71274b6ef96b]     51:         <% end %>
[eebfb355-8340-407c-8d76-71274b6ef96b]     52:       </div>
F, [2019-08-06T11:37:36.869210 #7] FATAL -- : [eebfb355-8340-407c-8d76-71274b6ef96b]
F, [2019-08-06T11:37:36.869297 #7] FATAL -- : [eebfb355-8340-407c-8d76-71274b6ef96b] app/models/sync.rb:97:in `description'
[eebfb355-8340-407c-8d76-71274b6ef96b] app/views/lists/show.html.erb:49:in `block in _app_views_lists_show_html_erb__3042575115678943902_47165430964760'
[eebfb355-8340-407c-8d76-71274b6ef96b] app/views/lists/show.html.erb:46:in `_app_views_lists_show_html_erb__3042575115678943902_47165430964760'
[eebfb355-8340-407c-8d76-71274b6ef96b] config/application.rb:20:in `call'
[eebfb355-8340-407c-8d76-71274b6ef96b] config/initializers/filter_external_domain_requests.rb:13:in `call'`

**Comment by michael-gratton** [comment]
Hey @declicromania, apologies for the very late reply. If you're running up-to-date Id and Spoke, then this repo should now be working fine for each.

If you're still seeing this please do let me know, but otherwise I'll assume it's been resolved.
